baseURL = 'https://theredwizardtower.com'
languageCode = 'en-us'
title = 'The Red Wizard Tower'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[taxonomies]
tag = 'tags'

[assets]
disableHLJS = true

[params]
author = "Valentin"
email = "hello@theredwizardtower.com"

# Social Icons
[[params.socialIcons]]
name = "linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/valentin-voina-4267b7308"

[[params.socialIcons]]
name = "reddit"
title = "Reddit"
url = "https://reddit.com/user/RevengerWizard"

[[params.socialIcons]]
name = "discord"
title = "Discord server"
url = "https://discord.gg/wdeJ8fydP3"

[[params.socialIcons]]
name = "twitter"
title = "Twitter"
url = "https://twitter.com/RevengerWizard"

[[params.socialIcons]]
name = "github"
title = "GitHub"
url = "https://github.com/RevengerWizard"

[[params.socialIcons]]
name = "email"
title = "Email"
url = "mailto:hello@theredwizardtower.com"

# Projects
[[params.projects]]
name = "Teascript"
title = "teascript"
year = 2022
description = """
A small stack-based bytecode interpreter written in C for a dynamically typed language."""
url = "https://github.com/RevengerWizard/teascript"

[[params.projects]]
name = "Viper"
title = "viper"
year = 2025
description = """
A compiler written in C for a statically compiled language."""
url = "https://github.com/RevengerWizard/viper"

[[params.projects]]
name = "Micro"
title = "micrö"
year = 2024
description = """
A pixel framework that uses Teascript as its scripting language; currently being rewritten in Viper."""
url = "https://github.com/RevengerWizard/micro"

[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 30

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 40
